Readme updates and Dockerfile updates
oduwsdl/CarbonDate pull request #9
Opened 2017-08-31 20:01 UTC by grantat

Updates to Readme and Dockerfile. More suggestions welcome.

2017-08-31 20:20 UTC, ibnesayeed commented on README.md
> +Name your module main script as cdGet\<Module name\>.py. If you module relies on extra code in a different folder it is alright to bring this directory into the modules directory, the carbon tool wil
Correct some typos and improve highlights here:

* module main => module's main
* cdGet\<Module name\>.py => `cdGet<ModuleName>.py`
* you module => your module
* carbon tool => CarbonDate library
* while loading => while loading modules
* ./modules folder => `./modules` folder
* 'SystemUtility' => `SystemUtility`

2017-08-31 20:21 UTC, ibnesayeed requested changes
Please correct some verbiage as indicated in the inline comment.

2017-09-01 22:12 UTC, grantat commented
Changes applied

2017-09-02 02:44 UTC, ibnesayeed requested changes
Some minor wording changes.

2017-09-02 02:44 UTC, ibnesayeed commented on README.md
> +Name your module's main script as `cdGet\<Module name\>.py`. If your module relies on extra code in a different folder you may bring this directory into the modules directory, the CarbonDate library
`cdGet\<Module name\>.py` => `cdGet<ModuleName>.py` (note the camelCase module name without a space, also escaping is unnecessary.)

Should "under `SystemUtility` field" be "under the `SystemUtility` field"?

2017-09-05 20:14 UTC, ibnesayeed commented
LGTM

2017-09-05 20:17 UTC, merged